# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.

#THIS JOB DEPLOYS TO PRODUCTION ONLY.  
# it should only be  run when a PR has been made into the master branch from anywhere
jobs:
  build:
    docker:
      - image:  circleci/node:14.15.3
    
    steps:
      - checkout
      - run:
          name: Create A Directory
          command: mkdir sfdx
      - run:
          name: Cd Into Directory
          command: cd sfdx
      - run:
          name: Download CLI
          command: |
            # Download cli
            wget -qO- $DX_CLI_URL | tar xJ -C sfdx --strip-components 1
      - run:
          name: Install CLI
          command: |
            # Install the cli
            ./sfdx/install
            sfdx

      - run:
          name: Display decryption key
          command: echo $DECRYPT_KEY | md5sum
      
      # to be sure that circle ci is really using the environment variables 
      - run:
          name: Decrypt server key
          command:
            openssl enc -aes-256-cbc -d -nosalt -base64 -in assets/server.key.enc -out assets/server.key -K "$DKEY" -iv "$DIV"
      - run:
          name: Authorize To Target Org
          command: sfdx force:auth:jwt:grant --instanceurl "$ENDPOINT" --clientid "$CLIENT_ID" --jwtkeyfile assets/server.key --username "$USERNAME"  --setalias ProdTest

      - run:
          name: Convert Source To Metadata Format
          command: sfdx force:source:convert --rootdir force-app --outputdir tmp_convert         
      - run:
          name: Create release artifact [zip]
          command: zip -r releaseartifact.zip tmp_convert
      - run:
          name: Delete metadata directory
          command: rm -r tmp_convert
      - run:
          name: Deploy release artifact [zip]
          command: sfdx force:mdapi:deploy --zipfile releaseartifact.zip --targetusername ProdTest --testlevel RunAllTestsInOrg --checkonly
      
      - run:
          name: Display deployment report
          command: sfdx force:mdapi:deploy:report -u ProdTest
      
      - run:
          name: Delete release artifact after deploy
          command: rm releaseartifact.zip 

                  

orbs:
  salesforce-sfdx: circleci/salesforce-sfdx@2.1.0


