# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.

jobs:
  build:
    docker:
      - image:  circleci/node:14.15.3
    
    steps:
      - checkout
      - run:
          name: Create A Directory
          command: mkdir sfdx
      - run:
          name: Cd Into Directory
          command: cd sfdx
      - run:
          name: Download CLI
          command: |
            # Download cli
            wget -qO- $DX_CLI_URL | tar xJ -C sfdx --strip-components 1
      - run:
          name: Install CLI
          command: |
            # Install the cli
            ./sfdx/install
            sfdx
      - run:
          name: Decrypt server key
          command:
            #Decrypt server key
            openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out assets/server.key -base64 -K $DECRYPT_KEY -iv $DECRYPT_IV    
      - run:
          name: Authorize To Target Org
          command: sfdx force:auth:jwt:grant --instanceurl $ENDPOINT --clientid $CLIENT_ID --jwtkeyfile assets/server.key --username $USERNAME  --setalias ProdTest

      - run:
          name: Echo Got Here
          command: echo " We have reached here"        

orbs:
  salesforce-sfdx: circleci/salesforce-sfdx@2.1.0


