public class FileUploader {
//brainstorm
//1. read file
//2. access excel file content (by index)
//3. assign values to fields of the required data 
//from the specified cell...
//.. of the excel file
//4.  write methods that insert the data using DMl (upload file method) 
//5. design the ui in a way to allow...
// ...for the process to happen (button to upload file)
    public static void uploadFile(){
        
        
        
    }
}